# Generated by Django 3.0.5 on 2023-07-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_slide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentName', models.CharField(max_length=200, null=True)),
                ('StudentId', models.CharField(max_length=50, null=True)),
                ('PhysicsMarks', models.IntegerField(null=True)),
                ('ChemistryMarks', models.IntegerField(null=True)),
                ('MathsMarks', models.IntegerField(null=True)),
                ('EnglishMarks', models.IntegerField(null=True)),
                ('ComputerMarks', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Slide',
        ),
    ]
