# Generated by Django 3.0.5 on 2023-11-02 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_teacherextra_assigned_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='marks',
            name='ChemistryMarks',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='ComputerMarks',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='EnglishMarks',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='MathsMarks',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='PhysicsMarks',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='StudentId',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='StudentName',
        ),
        migrations.AddField(
            model_name='marks',
            name='english',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='marks',
            name='math',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='marks',
            name='nepali',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='marks',
            name='science',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='marks',
            name='social',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='marks',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.StudentExtra'),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('due_date', models.DateField()),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.TeacherExtra')),
                ('assigned_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.Class')),
            ],
        ),
    ]
