# Generated by Django 3.0.5 on 2023-11-03 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_auto_20231103_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherextra',
            name='assigned_class',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
