# Generated by Django 3.0.5 on 2023-11-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_auto_20231103_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherextra',
            name='assigned_class',
            field=models.CharField(blank=True, choices=[('one', 'one'), ('two', 'two'), ('three', 'three'), ('four', 'four'), ('five', 'five'), ('six', 'six'), ('seven', 'seven'), ('eight', 'eight'), ('nine', 'nine'), ('ten', 'ten')], max_length=10),
        ),
    ]
