# Generated by Django 3.0.5 on 2023-11-03 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0020_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherextra',
            name='assigned_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.Class'),
        ),
    ]
