# Generated by Django 3.0.5 on 2023-11-03 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0022_auto_20231103_2321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='posted_by',
            new_name='assigned_by',
        ),
    ]
