# Generated by Django 3.0.5 on 2023-11-03 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0023_auto_20231103_2331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='name',
            new_name='class_name',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
