# Generated by Django 3.0.5 on 2023-11-04 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0026_postassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postassignment',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='PostAssignment',
        ),
    ]
