# Generated by Django 3.0.5 on 2023-11-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0027_auto_20231104_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('due_date', models.DateTimeField()),
            ],
        ),
    ]
