# Generated by Django 3.0.5 on 2023-11-04 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0028_assignment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='Marks',
        ),
    ]
